### ISSUE TITLE
Specifying default value (as literal) without implementing DefaultValueProvider protocol

### ISSUE THREAD

**Issue by Daemon-Devarshi** [gonzalezreal/DefaultCodable#4]
So if I have to define a default value of 1.0, I can implement something like this:

```
public enum OneDouble: DefaultValueProvider {
    public static let `default`: Double = 1.0
}
```

And use it like this:
```
public class Estimate: Codable {
    @Default<OneDouble>
    public var fees: Double
}
```

For some reasons if I decide to change the value to 0.5, then I have to change it or add another enum:

```
public enum PointFiveDouble: DefaultValueProvider {
    public static let `default`: Double = 0.5
}
```

This looks cumbersome to me.

Is there any way to just use it like this:

```
public class Estimate: Codable {
    @Default(0.5)
    public var fees: Double
}
```

**Comment by gonzalezreal** [comment]
Unfortunately, there is no way to use it as you propose. You could define a constructor in the property wrapper to pass the default value like that, but then it won't work with `Decodable` as this protocol defines its own constructor that the property wrapper must implement. Therefore, you need to define the default value as a type. Admittedly, not beautiful but convenient.

**Comment by Daemon-Devarshi** [comment]
Thanks for the reply! I understand the issue. I can use it as suggested, no worries.
