### ISSUE TITLE
Type 'XXX' does not conform to protocol 'Hashable'

### ISSUE THREAD

**Issue by skywalkerlw** [gonzalezreal/DefaultCodable#5]
Any suggestion on `Hashable`? Currently,  i have to remove `Hashable` in order to use `@Default<Empty>`

![image](https://user-images.githubusercontent.com/2090084/121519622-45ea6a00-ca35-11eb-897b-0c179ae3a0d3.png)

**Comment by gonzalezreal** [comment]
This is a bug and looks easy to fix. I will look into it as soon as I can.

**Comment by gonzalezreal** [comment]
This should be fixed in https://github.com/gonzalezreal/DefaultCodable/releases/tag/1.2.1

**Comment by skywalkerlw** [comment]
Thank you
