### ISSUE TITLE
Is it possible to support more types of Codable?

### ISSUE THREAD

**Issue by SF-Simon** [gonzalezreal/DefaultCodable#6]
Hi Guille

I love your open source projects, many of which are related to my work. Thank you for your work.

I'm working on a job implementing serialization and deserialization of NSFont and UIFont, aka Codable.

My code is like this:

```
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let font = self.wrappedValue{
            let descriptorData = try? NSKeyedArchiver.archivedData(withRootObject: font.fontDescriptor, requiringSecureCoding: false) 
            try container.encode(descriptorData, forKey: .descriptor)
            try container.encode(font.pointSize, forKey: .pointSize)
            try container.encode(font.fontName, forKey: .fontName)
        }
    }
```

After I saw your open source project, I really liked this way of writing.
So I would like to give a suggestion, is there any Codable that supports more types. For example: the relevant support type of NSKeyedUnarchiver.

Also, after this type of parsing fails, a default value is returned.

Just an idea, if you have the same idea, we might as well give it a try.

**Comment by gonzalezreal** [comment]
Sorry, I am not sure I understand your question. Could you please elaborate more on what you would like to achieve?

**Comment by SF-Simon** [comment]
I'm sorry, my English is really poor.

Currently this library class provides a default known type for non-null types. (As I understand it is)

But I think this default value, it should be mutable or freely fillable, as long as the type is consistent.

In addition, I mentioned other types, hoping to support other commonly used types but cocoa or uikit do not support serialization. Such as NSColor, UIColor, NSFont, UIFont, and subclasses of NSKeyedUnarchiver.

In this way, this package becomes an extension package, which can facilitate fault tolerance of missing values (provide default values) when deserializing, and also supports packaging of some more types so that they can be serialized and deserialized

**Comment by gonzalezreal** [comment]
I am sorry, but I still don't follow what you're trying to achieve. This package is designed to work with `Codable` types, not `NSCoding`.
